# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Deafult

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: gradle build
  displayName: 'Build with gradle'
- script: gradle run
  displayName: 'Running jar'
